services:
  nginx:
    image: nginx:1.25-alpine
    hostname: lb
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - node01
      - node02      
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"
  
  node01: 
    image: ghcr.io/rst77/app:9
    container_name: node01
    hostname: node01
    environment:
          PAYMENT_PROCESSOR_FALLBACK: http://lb:9999/sf
          PAYMENT_PROCESSOR_DEFAULT: http://lb:9999/sd
          NODE_ID: node01
    networks:
      - payment-processor
      - rinha-net

    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "170MB"

  node02: 
    image: ghcr.io/rst77/app:9
    container_name: node02
    hostname: node02
    environment:
          PAYMENT_PROCESSOR_FALLBACK: http://lb:9999/sf
          PAYMENT_PROCESSOR_DEFAULT: http://lb:9999/sd
          NODE_ID: node02
    networks:
      - payment-processor
      - rinha-net

    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "170MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge

