x-backend-templates:
  app: &app
    image: ghcr.io/rst77/app:99
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "160MB"

  app-env: &app-env  
    PAIR_NBR: 2
    PAYMENT_PROCESSORS: 
    CONN_TO: "60"
    REQ_TO: "15"
    SUMM_DELAY: "1000"
    #PAYMENT_PROCESSOR_FALLBACK: http://lb:9999/pf
    #PAYMENT_PROCESSOR_DEFAULT: http://lb:9999/pd
    PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
    PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080

services:
  nginx:
    image: nginx:1.25-alpine
    hostname: lb
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - node01
      - node02
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "20MB"
  
  node01: 
    <<: *app
    container_name: node01
    hostname: node01
    ports:
      - "5001:5000"
    environment:
          <<: *app-env
          NODE_ID: 1

  node02: 
    <<: *app
    container_name: node02
    hostname: node02
    environment:
          <<: *app-env
          NODE_ID: 2

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge

