version: "3.9"

services:
  
  api01: &api
    image: ghcr.io/rst77/devpr2025/cli-app:2
    hostname: api01
    environment:
          LB_URL: lb-server
          PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
          PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080    
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - lb      
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02

  lb:
    hostname: lb-server
    image: ghcr.io/rst77/devpr2025/api-app:2
    environment:
          PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
          PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080    
    ports:
      - "9999:9999"
      - "5000:5000"
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge